export const payrollSimulationDefaults = {
  minimoContrattuale: 2137.04,
  apa: 0,
  salarioProfessionale: 142.54,
  salarioProduttivita: 88,
  eurofer: 65.49,
  detrazioniLavoroDipendente: 0,
  aliquotaINPS: 0.0816,
  aliquotaAddizionaleRegionale: 0.0257,
  aliquotaAddizionaleComunale: 0.0094,
  payrollRole: "BORDO",
};

export const payrollRoleDefaults = {
  BORDO: {
    label: "Bordo",
    description: "Capotreno / Capo Servizi Treno",
    salarioProfessionale: 142.54,
  },
  MACCHINA: {
    label: "Macchina",
    description: "Macchinista",
    salarioProfessionale: 208.96,
  },
};

export const variablePayrollRates = {
  vettureEccedenti: 1.15,
  scortaDiurnaAgenteDoppio: 2.4,
  scortaNotturnaAgenteDoppio: 4.7,
  scortaDiurnaAgenteUnico: 3.5,
  scortaNotturnaAgenteUnico: 6,
  iupRiservaFormazione: 4.5,
  iupAssenze: 4.5,
  indennitaPernottazione: 2.8,
  festivitaDicembreAnnoPrecedente: 20,
  indennitaTurnoB: 2.45,
  indennitaLavoroNotturno: 2.5,
  completamentoFineCorsa: 18,
  indennitaDomenicale: 23.5,
  assResAR: 1.6,
  assResRFR: 2.6,
};

export const diarySimulationCodeMap = {
  "0547": "vettureEccedenti",
  "0969": "scortaDiurnaAgenteDoppio",
  "0970": "scortaNotturnaAgenteDoppio",
  "0AD0": "scortaDiurnaAgenteUnico",
  "0AD1": "scortaNotturnaAgenteUnico",
  "0790": "iupRiservaFormazione",
  "0792": "iupAssenze",
  "0286": "straordinarioFerialeNotturnoFestivoDiurno",
  "0353": "festivitaDicembreAnnoPrecedente",
  "0377": "indennitaTurnoB",
  "0412": "indennitaPernottazione",
  "0421": "indennitaLavoroNotturno",
  "0457": "indennitaDomenicale",
  "0991": "assResAR",
  "0992": "assResRFR",
  "0299": "ticket",
  "0134": "pieDiLista",
};

export const simulationFieldLabels = {
  vettureEccedenti: "Vetture eccedenti",
  scortaDiurnaAgenteDoppio: "Scorta diurna agente doppio",
  scortaNotturnaAgenteDoppio: "Scorta notturna agente doppio",
  scortaDiurnaAgenteUnico: "Scorta diurna agente unico",
  scortaNotturnaAgenteUnico: "Scorta notturna agente unico",
  iupRiservaFormazione: "IUP riserva/formazione",
  iupAssenze: "IUP assenze PDM/PDB",
  indennitaPernottazione: "Indennita pernottazione",
  festivitaDicembreAnnoPrecedente: "Festivita dicembre anno precedente",
  straordinarioFerialeDiurno: "Straordinario feriale diurno",
  straordinarioFerialeNotturnoFestivoDiurno: "Straordinario feriale notturno/festivo diurno",
  straordinarioFestivoNotturno: "Straordinario festivo notturno",
  straordinarioMensile: "Straordinario mensile 20%",
  indennitaTurnoB: "Indennita turno B",
  indennitaLavoroNotturno: "Indennita lavoro notturno",
  indennitaLavoroFestivo: "Indennita lavoro festivo",
  completamentoFineCorsa: "Completamento fine corsa",
  indennitaDomenicale: "Indennita domenicale",
  assResAR: "Ass. res. A/R",
  assResRFR: "Ass. res. RFR",
  ticket: "Ticket",
  pieDiLista: "Pie di lista",
  biglietteria: "Biglietteria",
};
