const fs = require('node:fs');
const path = require('node:path');
require('./register-source.cjs');
const { routes, aliases, SITE_URL } = require('../src/seo/metadata');
const publicDirectory = path.resolve(__dirname, '../public');
const escapeXml = value => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const urls = Object.entries(routes).filter(([, page]) => !page.noindex).map(([route]) => `  <url><loc>${escapeXml(SITE_URL + route)}</loc></url>`);
fs.writeFileSync(path.join(publicDirectory, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`);
const redirects = [
  '# Generated by npm run seo:assets. Route policy: src/seo/metadata.js and routes.json.',
  '/Servizi /servizi 301!',
  '/index.html / 301!',
  ...Object.keys(routes).filter(route => route !== '/').map(route => `${route}.html ${route} 301!`),
  ...Object.entries(aliases).map(([from, to]) => `${from} ${to} 301!`),
  '# Only registered pages receive a 200 rewrite. Netlify normalizes slash matching.',
  ...Object.keys(routes).filter(route => route !== '/').map(route => `${route} ${route}.html 200!`),
  '# Real files and Netlify Functions remain available; missing paths use 404.html.',
];
fs.writeFileSync(path.join(publicDirectory, '_redirects'), redirects.join('\n') + '\n');
console.log(`SEO assets: ${urls.length} indexable URLs; ${Object.keys(routes).length} public routes.`);
